import { Banknote, FileText, Search, WalletCards } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";

import { DeductionPolicyDialog, DeletePayrollTranscriptButton, PayrollTranscriptDialog } from "@/components/payroll/payroll-forms";
import { displayPayrollUid } from "@/features/payroll/identifiers";
import { getPayrollWorkspace } from "@/features/payroll/queries";

export const metadata: Metadata = { title: "Payroll transcripts" };
function first(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
function personLabel(person: { firstName: string | null; lastName: string | null; username: string | null; email: string | null }) { return [person.firstName, person.lastName].filter(Boolean).join(" ") || person.username || person.email || "Team member"; }
function money(value: { toString(): string } | null) { return new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", minimumFractionDigits: 2 }).format(Number(value?.toString() ?? 0)); }
function monthLabel(value: Date) { return value.toLocaleDateString("en-GB", { timeZone: "UTC", month: "long", year: "numeric" }); }
function pakistanDateParts() { const values = new Intl.DateTimeFormat("en-US", { timeZone: "Asia/Karachi", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date()); const part = (type: Intl.DateTimeFormatPartTypes) => values.find((item) => item.type === type)?.value ?? ""; return { date: `${part("year")}-${part("month")}-${part("day")}`, month: `${part("year")}-${part("month")}` }; }

export default async function PayrollPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams;
  const data = await getPayrollWorkspace({ query: first(raw.query), profileId: first(raw.profileId), payPeriod: first(raw.payPeriod), page: first(raw.page) });
  if (!data) redirect("/dashboard");
  const now = pakistanDateParts();
  const staff = data.staff.map((profile) => ({ id: profile.id, label: personLabel(profile), phone: profile.phone ?? "" }));
  const policy = data.policy ? { lateArrivals: data.policy.lateArrivals, halfDays: data.policy.halfDays, daysOff: data.policy.daysOff, effectiveFrom: data.policy.effectiveFrom.toISOString().slice(0, 10) } : null;
  const pageHref = (page: number) => ({ pathname: "/payroll", query: { query: data.filters.query, profileId: data.filters.profileId, payPeriod: data.filters.payPeriod, page: page > 1 ? String(page) : undefined } });
  return <div className="mx-auto w-full max-w-[1500px] font-sans"><nav className="flex items-center gap-1 text-xs text-gray-500 sm:text-sm"><Link href="/dashboard" className="hover:text-[#20aee3]">Dashboard</Link><span>›</span><span>Transcript</span></nav><div className="mt-2 flex flex-col justify-between gap-4 pb-5 lg:flex-row lg:items-center lg:pb-8"><div><h1 className="text-[28px] font-light text-[#20aee3] sm:text-[32px]">Salary Transcripts</h1><p className="mt-1 text-xs text-gray-400">Create accurate salary slips with versioned attendance deductions.</p></div><div className="flex flex-wrap gap-2"><DeductionPolicyDialog policy={policy} today={now.date} /><PayrollTranscriptDialog staff={staff} policy={policy} month={now.month} /></div></div>
    {!policy ? <p className="mb-5 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-700">Create deduction rates before generating the first salary transcript.</p> : <p className="mb-5 rounded-lg border border-sky-100 bg-sky-50 px-4 py-3 text-xs text-sky-700">Current rates effective {new Date(`${policy.effectiveFrom}T00:00:00.000Z`).toLocaleDateString("en-GB", { timeZone: "UTC" })}: late arrival {money({ toString: () => String(policy.lateArrivals) })}, half day {money({ toString: () => String(policy.halfDays) })}, default day off {money({ toString: () => String(policy.daysOff) })}.</p>}
    <section className="mb-5 grid gap-3 sm:grid-cols-3">{[{ label: "Salary slips", value: String(data.totals.count), icon: FileText }, { label: "Total gross", value: money(data.totals.gross), icon: Banknote }, { label: "Total net", value: money(data.totals.net), icon: WalletCards }].map(({ label, value, icon: Icon }) => <article key={label} className="surface-card flex items-center gap-4 rounded-lg p-4"><span className="flex size-10 items-center justify-center rounded-lg bg-sky-50 text-[#20aee3]"><Icon className="size-5" /></span><div><p className="text-lg font-medium text-gray-700">{value}</p><p className="text-xs text-gray-400">{label}</p></div></article>)}</section>
    <section className="surface-card mb-4 rounded-lg p-3 sm:p-4"><form action="/payroll" className="grid gap-3 lg:grid-cols-[1fr_220px_180px_auto]"><label className="relative"><Search className="absolute left-3 top-3 size-4 text-gray-400" /><span className="sr-only">Search transcripts</span><input name="query" defaultValue={data.filters.query} placeholder="ID, employee, phone, designation…" className="h-10 w-full rounded-md border border-gray-200 bg-[#f8fbfc] pl-9 pr-3 text-sm outline-none focus:border-[#20aee3]" /></label><select name="profileId" defaultValue={data.filters.profileId ?? ""} className="h-10 rounded-md border border-gray-200 bg-white px-3 text-sm text-gray-600"><option value="">All employees</option>{staff.map((member) => <option key={member.id} value={member.id}>{member.label}</option>)}</select><input name="payPeriod" type="month" defaultValue={data.filters.payPeriod ?? ""} className="h-10 rounded-md border border-gray-200 bg-white px-3 text-sm text-gray-600" /><div className="flex gap-2"><button className="h-10 flex-1 rounded-md bg-[#20aee3] px-4 text-sm font-medium text-white">Apply</button><Link href="/payroll" className="inline-flex h-10 items-center rounded-md border border-gray-200 px-4 text-sm text-gray-600">Clear</Link></div></form></section>
    <section className="surface-card overflow-hidden rounded-lg p-3 sm:p-[15px]"><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1000px] border-collapse text-left text-sm font-light text-gray-700"><thead><tr className="border-b border-gray-200 text-[#20aee3]"><th className="px-3 py-4 font-medium">ID</th><th className="px-3 py-4 font-medium">Employee</th><th className="px-3 py-4 font-medium">Designation</th><th className="px-3 py-4 font-medium">Phone</th><th className="px-3 py-4 font-medium">Salary Month</th><th className="px-3 py-4 font-medium">Salary Type</th><th className="px-3 py-4 font-medium">Total Salary</th><th className="px-3 py-4 font-medium">Net Salary</th><th className="px-3 py-4 font-medium">Action</th></tr></thead><tbody>{data.transcripts.length === 0 ? <tr><td colSpan={9} className="px-3 py-16 text-center text-gray-400">No salary transcripts match this view.</td></tr> : data.transcripts.map((item) => <tr key={item.id} className="border-b border-gray-100 transition hover:bg-[#f4fafc]"><td className="whitespace-nowrap px-3 py-4 font-medium">{displayPayrollUid(item.uid, item.id)}</td><td className="px-3 py-4 capitalize">{item.employeeName}</td><td className="px-3 py-4">{item.designation ?? "—"}</td><td className="px-3 py-4">{item.phone ?? "—"}</td><td className="whitespace-nowrap px-3 py-4">{monthLabel(item.payPeriodStart)}</td><td className="px-3 py-4 capitalize">{item.salaryType?.toLowerCase() ?? "—"}</td><td className="whitespace-nowrap px-3 py-4">{money(item.totalSalary)}</td><td className="whitespace-nowrap px-3 py-4 font-medium text-emerald-600">{money(item.netSalary)}</td><td className="px-3 py-4"><div className="flex items-center gap-1"><Link href={`/payroll/${item.id}/print`} className="rounded-md border border-emerald-100 px-2.5 py-1.5 text-xs text-emerald-600 hover:bg-emerald-50">Print</Link><DeletePayrollTranscriptButton transcriptId={item.id} /></div></td></tr>)}</tbody></table></div>
      <div className="grid gap-3 lg:hidden">{data.transcripts.length === 0 ? <div className="rounded-lg border border-dashed border-gray-200 px-4 py-14 text-center text-sm text-gray-400">No salary transcripts match this view.</div> : data.transcripts.map((item) => <article key={item.id} className="rounded-lg border border-gray-100 bg-[#fbfdfe] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium capitalize text-gray-700">{item.employeeName}</p><p className="mt-1 text-xs text-gray-400">{displayPayrollUid(item.uid, item.id)} · {monthLabel(item.payPeriodStart)}</p></div><span className="rounded-full border border-sky-200 bg-sky-50 px-2 py-1 text-[10px] capitalize text-sky-700">{item.salaryType?.toLowerCase() ?? "salary"}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-gray-400">Gross</dt><dd className="mt-1 text-gray-700">{money(item.totalSalary)}</dd></div><div><dt className="text-gray-400">Net</dt><dd className="mt-1 font-medium text-emerald-600">{money(item.netSalary)}</dd></div><div><dt className="text-gray-400">Designation</dt><dd className="mt-1 text-gray-700">{item.designation ?? "—"}</dd></div><div><dt className="text-gray-400">Phone</dt><dd className="mt-1 text-gray-700">{item.phone ?? "—"}</dd></div></dl><div className="mt-3 flex justify-end gap-1 border-t border-gray-100 pt-3"><Link href={`/payroll/${item.id}/print`} className="rounded-md border border-emerald-100 px-3 py-2 text-xs text-emerald-600">Print</Link><DeletePayrollTranscriptButton transcriptId={item.id} /></div></article>)}</div></section>
    <nav className="mt-5 flex items-center justify-between rounded-lg border border-gray-100 bg-white px-4 py-3 text-sm shadow-sm"><span className="text-xs text-gray-500">Page {data.pagination.page}</span><div className="flex gap-2">{data.pagination.hasPrevious ? <Link href={pageHref(data.pagination.page - 1)} className="rounded-md border border-gray-200 px-3 py-2 text-gray-600">Previous</Link> : <span className="rounded-md border border-gray-100 px-3 py-2 text-gray-300">Previous</span>}{data.pagination.hasNext ? <Link href={pageHref(data.pagination.page + 1)} className="rounded-md border border-gray-200 px-3 py-2 text-gray-600">Next</Link> : <span className="rounded-md border border-gray-100 px-3 py-2 text-gray-300">Next</span>}</div></nav>
  </div>;
}
