import { notFound, redirect } from "next/navigation";

import { BrandWordmark } from "@/components/brand-wordmark";
import { PrintPayrollButton } from "@/components/payroll/print-payroll-button";
import { displayPayrollUid } from "@/features/payroll/identifiers";
import { getPrintablePayrollTranscript } from "@/features/payroll/queries";

function money(value: { toString(): string } | string | null) { const raw = typeof value === "string" ? value : value?.toString() ?? "0"; return new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", minimumFractionDigits: 2 }).format(Number(raw)); }
function deduction(value: string | null) { return value ? `-${money(value)}` : "—"; }

export default async function PrintablePayrollPage({ params }: { params: Promise<{ transcriptId: string }> }) {
  const { transcriptId } = await params;
  const data = await getPrintablePayrollTranscript(transcriptId);
  if (!data) redirect("/dashboard");
  if (!data.transcript) notFound();
  const item = data.transcript;
  const calculation = data.calculation;
  const totalDeductions = calculation?.totalDeductions ?? (item.totalSalary && item.netSalary ? item.totalSalary.sub(item.netSalary).toFixed(2) : null);
  const cell = "border border-slate-300 px-4 py-3";
  return <main className="min-h-screen bg-slate-100 px-3 py-6 print:bg-white print:p-0"><div className="mx-auto mb-4 flex max-w-[900px] justify-end print:hidden"><PrintPayrollButton /></div><article className="mx-auto min-h-[1100px] max-w-[900px] bg-white p-8 text-slate-800 shadow-xl print:min-h-0 print:max-w-none print:p-0 print:shadow-none sm:p-12"><header className="flex items-start justify-between gap-8 border-b-2 border-slate-800 pb-6"><BrandWordmark className="text-2xl" /><table className="text-sm"><tbody><tr><th className={`${cell} bg-slate-100 text-left`}>Transcript No.</th><td className={cell}>{displayPayrollUid(item.uid, item.id)}</td></tr><tr><th className={`${cell} bg-slate-100 text-left`}>Date of issue</th><td className={cell}>{item.createdAt.toLocaleDateString("en-GB", { dateStyle: "long" })}</td></tr></tbody></table></header><h1 className="my-8 text-center text-2xl font-semibold uppercase tracking-[0.18em]">Salary Transcript</h1>
    <table className="w-full table-fixed border-collapse text-sm"><tbody><tr>{["Employee", "Salary Month", "Designation"].map((title) => <th key={title} className={`${cell} bg-slate-100`}>{title}</th>)}</tr><tr><td className={`${cell} text-center capitalize`}>{item.employeeName}</td><td className={`${cell} text-center`}>{item.payPeriodStart.toLocaleDateString("en-GB", { timeZone: "UTC", month: "long", year: "numeric" })}</td><td className={`${cell} text-center`}>{item.designation ?? "—"}</td></tr><tr>{["Salary Type", "Phone", "Employee ID"].map((title) => <th key={title} className={`${cell} bg-slate-100`}>{title}</th>)}</tr><tr><td className={`${cell} text-center capitalize`}>{item.salaryType?.toLowerCase() ?? "—"}</td><td className={`${cell} text-center`}>{item.phone ?? "—"}</td><td className={`${cell} text-center`}>{item.profileId?.slice(0, 8).toUpperCase() ?? "—"}</td></tr></tbody></table>
    <table className="mt-8 w-full border-collapse text-sm"><thead><tr><th className={`${cell} bg-slate-100 text-left`}>Earnings / deductions</th><th className={`${cell} bg-slate-100 text-right`}>Calculation</th><th className={`${cell} bg-slate-100 text-right`}>Amount</th></tr></thead><tbody><tr><td className={cell}>Total salary</td><td className={`${cell} text-right`}>Gross</td><td className={`${cell} text-right font-medium`}>{money(item.totalSalary)}</td></tr><tr><td className={cell}>Late arrivals</td><td className={`${cell} text-right`}>{item.lateArrivals ?? 0} × {calculation?.lateArrivalRate ? money(calculation.lateArrivalRate) : "—"}</td><td className={`${cell} text-right text-rose-600`}>{deduction(calculation?.lateArrivalDeduction ?? null)}</td></tr><tr><td className={cell}>Half days</td><td className={`${cell} text-right`}>{item.halfDays ?? 0} × {calculation?.halfDayRate ? money(calculation.halfDayRate) : "—"}</td><td className={`${cell} text-right text-rose-600`}>{deduction(calculation?.halfDayDeduction ?? null)}</td></tr><tr><td className={cell}>Days off</td><td className={`${cell} text-right`}>{item.daysOff ?? 0} × {money(item.amountPerDayOff)}</td><td className={`${cell} text-right text-rose-600`}>{deduction(calculation?.dayOffDeduction ?? null)}</td></tr><tr><th className={`${cell} text-left`}>Total deductions</th><td className={cell}></td><td className={`${cell} text-right font-medium text-rose-600`}>{deduction(totalDeductions)}</td></tr><tr><th className={`${cell} bg-emerald-50 text-left text-emerald-800`}>Net salary</th><td className={`${cell} bg-emerald-50`}></td><td className={`${cell} bg-emerald-50 text-right text-lg font-semibold text-emerald-700`}>{money(item.netSalary)}</td></tr></tbody></table>
    <section className="mt-24 grid grid-cols-2 gap-16 text-center text-sm"><div className="border-t border-slate-700 pt-2">Authorized signature</div><div className="border-t border-slate-700 pt-2">Employee signature</div></section><footer className="mt-20 border-t border-slate-200 pt-5 text-center text-xs leading-5 text-slate-500"><p>crm.mimico.live</p><p>info@marcablesolution.com · 301, 2nd Floor, Gulberg III, Lahore, Pakistan</p></footer></article></main>;
}
